### ISSUE TITLE
Updated list of valid emojis

### ISSUE THREAD

**Issue by alcor** [UCYT5040/Google-Sticker-Mashup-Research#6]
Attached is a refined list that should contain the latest currently valid emojis

[emojis.txt](https://github.com/UCYT5040/Google-Sticker-Mashup-Research/files/9628852/emojis.txt)

**Comment by UCYT5040** [comment]
Hey, could you make this a PR instead?

If you aren't able to I can run the script myself, it's just easier to have a PR.

Thanks

**Comment by UCYT5040** [comment]
@alcor Please read the above message.

**Comment by alcor** [comment]
Apologies - I don't have a good way of running the original script myself (I use a modified version that runs in a Google sheet), but I thought I'd share an updated list of known good ones :‌)

**Comment by UCYT5040** [comment]
Oh, I see. I'll run it myself, no worries.

**Comment by UCYT5040** [comment]
Hey, I'd like to apologize for taking so long to update this. Running the script right now with the updated list.

**Comment by UCYT5040** [comment]
Just wanted to update you, I still haven't done this because the script is very slow for me. I'm making improvements but it is still slower. Going to try and leave it overnight.
